[project]
name = "trip-planner-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aditya13696", email = "sawant.adi79@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
trip-planner-langgraph = "trip_planner_langgraph:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
